import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="Max-w-3xl mx-100 text-slate-800">
          <header className="p-6 border-b flex items-center justify-between bg-purple-400 
          rounded-bl-lg rounded-br-lg">
            <a className="text-2xl font-bold" href={"/"}> Product Details </a>
            <a className="bg-slate-100 grid place-items-center py-2 px-4 rounded-full font-bold shadow-md"  href={'/create'}> Add new Product </a>

          </header>
          <main className="p-5 text-lg">
          {children}
          </main>
          </div>
      </body>
    </html>
  );
}
